[workspace]
authors = ["Wolf Vollprecht <wolfv@prefix.dev>"]
channels = ["https://prefix.dev/conda-forge"]
description = "Showcases how to build a Rust project with pixi"
name = "build-rust"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]
version = "0.1.0"

[package]
# authors = ["Nichita Morcotilo <nichita@prefix.dev>"]
# description = "Showcases how to build a python project with pixi"
name = "build-rust"
version = "0.1.0"

[dependencies]
build-rust = { path = "." }

[package.build]
backend = { name = "pixi-build-rust", version = "*" }
channels = ["https://prefix.dev/pixi-build-backends", "https://prefix.dev/conda-forge"]
