package:
  name: linkerd
  version: 25.5.2

source:
  - if: linux and x86_64
    then:
      url: https://github.com/linkerd/linkerd2/releases/download/edge-25.5.2/linkerd2-cli-edge-25.5.2-linux-amd64
      sha256: 55e7721ab0eb48217f239628b55517b7d663a962df18cdab180e5d42e45f83cb
      file_name: linkerd
  - if: osx and arm64
    then:
      url: https://github.com/linkerd/linkerd2/releases/download/edge-25.5.2/linkerd2-cli-edge-25.5.2-darwin-arm64
      sha256: 405ddf3af0089bfece93d811c9bfb9f63e3a000e3f423163fc56690ef4d427cf
      file_name: linkerd

build:
  script:
    - chmod +x linkerd
    - mkdir -p $PREFIX/bin
    - mv linkerd $PREFIX/bin/ 

tests:
  - script:
      - linkerd version
      # can add more tests here

about:
  homepage: https://linkerd.io/
  license: Apache-2.0
  summary: Linkerd is an ultralight service mesh for Kubernetes.
  description: |
    Linkerd is an ultralight service mesh for Kubernetes. It adds observability, reliability, and security to your applications without requiring any code changes. Linkerd is open source and free to use.
  license_file: LICENSE
  # documentation: ...
  repository: https://github.com/linkerd/linkerd2